replicaCount: 1

image:
  repository: 450876623734.dkr.ecr.us-east-1.amazonaws.com/simulation-catalogue/api
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

livenessProbe:
  httpGet:
    path: /api/v1/public/version
    port: 8080
readinessProbe:
  httpGet:
    path: /api/v1/public/health
    port: 8080

ingress:
  enabled: true
  tls:
  - secretName: tls-cert
    hosts:
      - simulation-catalogue.s31-software.com

env:
  LOG_LEVEL: info

secrets: {}
